### ISSUE TITLE
红色问题解决了吗

### ISSUE THREAD

**Issue by LiJian-China** [joguo/MaliangMTK#1]

**Comment by joguo** [comment]
未解决，我这里验证是macOS 10.15系统的bug。

**Comment by LiJian-China** [comment]
应该不是系统的bug  我的是macOS 10.14 依然有这个问题

**Comment by joguo** [comment]
我这边是MacBook pro 10.15 红色，换iMac 10.14 正常。差异点是 系统不同 和 显示器是否retina。

**Comment by LiJian-China** [comment]
setFragmentTexture    这是全局纹理的导致的红色，draw回调方法里

**Comment by LiJian-China** [comment]
setFragmentTexture 设置全局纹理的导致的红色，draw回调方法里

**Comment by LiJian-China** [comment]
> 我这边是MacBook pro 10.15红色，换iMac 10.14正常。差异点是系统不同和显示器是否retina。
最终的解决方法是啥   不能只在iMac上用吧 哈哈哈

**Comment by LiJian-China** [comment]
> 我这边是MacBook pro 10.15红色，换iMac 10.14正常。差异点是系统不同和显示器是否retina。

我这边的解决方案是 通过纯透明的一个图片，来创建一个空纹理，然后setFragmentTexture设置上就行了

**Comment by joguo** [comment]
好的，我也测下。

**Comment by Zss1990** [comment]
> > 我这边是MacBook pro 10.15红色，换iMac 10.14正常。差异点是系统不同和显示器是否retina。
> 
> 我这边的解决方案是 通过纯透明的一个图片，来创建一个空纹理，然后setFragmentTexture设置上就行了

您好，使用`Canvas`是这样设置一张透明图片吗？
` if  let textureURL = Bundle.main.url(forResource: "touming.png", withExtension: nil){
            do {
                let data = try Data(contentsOf: textureURL)
                let chartlet = try canvas.makeTexture(with: data)
                let location = CGPoint(x: canvas.size.width/2.0, y: canvas.size.height/2.0)
                canvas.renderChartlet(at: location, size: canvas.size, textureID: chartlet.id)
            } catch  {
                print("texure load error")
            }
        }`

**Comment by bbaiqq** [comment]
代码中只要使用nextDrawable，基本就是红色，必须使用currentDrawable。
renderPassDescriptor.colorAttachments[0].texture 只能为 currentDrawable?.texture
